/* Source unique des projets — chargée par l'index et par chaque page projet.
   Règle : une valeur inconnue vaut null, jamais une valeur plausible.
   w / h / ar / plafond_encre sont recopiés depuis outils/manifest.json (produit par outils/derive.py).
   Les champs `z / col / span / y` décrivent la place du document dans le champ de l'index (index: true). */
window.PROJETS = [
  {
    slug: 'habiter-produire-partager', code: 'hpp', ordre: 1, etat: 'publie',
    numero: '02.1', axe: 'habiter',
    titre: 'habiter, produire, partager',
    programme: 'habitat collectif autosuffisant',
    cadre: 'atelier II · LOCI UCLouvain', annee: '2025-2026',
    equipe: ['hamza el arja'],
    lieu: { nom: 'bruxelles', coord: null },
    structure: 'bois, rez en béton et parement de brique',
    surface: null,
    aConfirmer: ['lieu', 'surface'],
    page: 'projets/habiter-produire-partager.html',
    documents: [
      { id: 'hpp-coupe-50', nature: 'coupe transversale 1:50', type: 'dessin', w: 2787, h: 2070, ar: 1.3464, plafond_encre: 148,
        alt: "coupe transversale — la serre de culture occupe la toiture, les logements s'organisent dessous",
        legende: 'la serre coiffe les logements — cultures suspendues sous le faîte, potagers sur les terrasses',
        largeur: 'pleine', index: true, cle: true, z: 0, col: 0, span: 7, y: 0 },
      { id: 'hpp-elevation', nature: 'élévation sur rue', type: 'dessin', w: 2906, h: 650, ar: 4.4708, plafond_encre: 66,
        alt: 'élévation sur rue — le projet inséré dans le front bâti',
        legende: 'sur la rue, le projet reprend les hauteurs de ses voisins',
        largeur: 'pleine', index: true, z: 2, col: 1, span: 11, y: 6.4 },
      { id: 'hpp-coupe-urbaine', nature: 'coupe urbaine', type: 'dessin', w: 2906, h: 871, ar: 3.3364, plafond_encre: 228,
        alt: "coupe urbaine à travers l'îlot",
        legende: "la traversée de l'îlot — le projet s'abaisse pour laisser entrer le jardin",
        largeur: 'pleine', index: true, z: 0, col: 0, span: 7, y: 15.9 },
      { id: 'hpp-implantation', nature: "plan d'implantation", type: 'dessin', w: 2908, h: 2245, ar: 1.2953, plafond_encre: 53,
        alt: "plan d'implantation — les deux maisons et le jardin productif dans l'îlot",
        legende: 'deux maisons tenues par le jardin productif, dans la profondeur de la parcelle',
        largeur: 'pleine', index: false },
      { id: 'hpp-plan-rdc-100', nature: 'plan du rez-de-chaussée 1:100', type: 'dessin', w: 1466, h: 1251, ar: 1.1719, plafond_encre: 235,
        alt: 'plan du rez-de-chaussée',
        legende: 'au rez, les espaces communs s\'ouvrent de plain-pied sur le jardin',
        largeur: 'demie', paire: 'niveaux-1', index: false },
      { id: 'hpp-plan-r1-100', nature: 'plan du premier étage 1:100', type: 'dessin', w: 1462, h: 1252, ar: 1.1677, plafond_encre: 237,
        alt: 'plan du premier étage',
        legende: "à l'étage, les chambres et la terrasse commune",
        largeur: 'demie', paire: 'niveaux-1', index: false },
      { id: 'hpp-plan-r2-100', nature: 'plan du deuxième étage 1:100', type: 'dessin', w: 1464, h: 1246, ar: 1.175, plafond_encre: 238,
        alt: 'plan du deuxième étage',
        legende: 'au deuxième, les logements sous la serre',
        largeur: 'demie', paire: 'niveaux-2', index: false },
      { id: 'hpp-plan-r3-100', nature: 'plan du troisième étage 1:100', type: 'dessin', w: 1464, h: 1249, ar: 1.1721, plafond_encre: 231,
        alt: 'plan du troisième étage — la serre de production',
        legende: 'au dernier niveau, la serre de production et ses tables de culture',
        largeur: 'demie', paire: 'niveaux-2', index: false },
      { id: 'hpp-plan-r1', nature: 'plan du premier étage 1:50', type: 'dessin', w: 2787, h: 1646, ar: 1.6932, plafond_encre: 84,
        alt: 'plan détaillé du premier étage au 1:50',
        legende: 'le premier étage en détail, de la rue au jardin',
        largeur: 'pleine', index: false },
      { id: 'hpp-axonometrie', nature: 'axonométrie éclatée', type: 'dessin', w: 906, h: 1152, ar: 0.7865, plafond_encre: 126,
        alt: 'axonométrie éclatée structurelle — structure ponctuelle en bois, rez en béton et parement de brique',
        legende: 'trois régimes constructifs — béton et brique au rez, poteaux-poutres en bois, serre légère au faîte',
        largeur: 'tiers', index: true, z: 1, col: 7, span: 4, y: 2.6 },
      { id: 'hpp-croquis', nature: 'croquis de recherche', type: 'dessin', w: 800, h: 1357, ar: 0.5895, plafond_encre: 95,
        alt: 'croquis de recherche — espaces partagés, marché ouvert au quartier, jardin collectif',
        legende: 'premières intentions — les seuils du commun, le marché ouvert au quartier',
        largeur: 'tiers', index: false },
      { id: 'hpp-cycle', nature: 'diagramme du cycle', type: 'dessin', w: 2476, h: 1388, ar: 1.7839, plafond_encre: 104,
        alt: 'diagramme du cycle de fonctionnement, de la gouvernance associative au marché mensuel',
        legende: 'le fonctionnement en boucle — produire, transformer, partager, réinvestir',
        largeur: 'pleine', index: true, z: 2, col: 3, span: 6, y: 11.3 },
      { id: 'hpp-analyse-verts', nature: "carte d'analyse — espaces verts", type: 'dessin', w: 1388, h: 1261, ar: 1.1007, plafond_encre: 183,
        alt: "carte d'analyse — espaces verts et jardinage accessibles au quartier",
        legende: 'ce que le quartier offre déjà — parcs, potagers collectifs et aires de jeux à 400 m du site',
        largeur: 'pleine', index: true, z: 1, col: 7, span: 5, y: 9.6 },
      { id: 'hpp-analyse-alimentation', nature: "carte d'analyse — alimentation", type: 'dessin', w: 950, h: 976, ar: 0.9734, plafond_encre: 155,
        alt: "carte d'analyse — accès à une alimentation de qualité",
        legende: 'où l\'on se nourrit — circuits courts et commerces autour du site',
        largeur: 'demie', paire: 'analyses', index: false },
      { id: 'hpp-analyse-bati', nature: "carte d'analyse — hauteur du bâti", type: 'dessin', w: 1056, h: 1095, ar: 0.9644, plafond_encre: 136,
        alt: "carte d'analyse — hauteur du bâti",
        legende: 'les gabarits du tissu, du rez aux quinze mètres',
        largeur: 'demie', paire: 'analyses', index: false },
      { id: 'hpp-narration', nature: 'narration graphique', type: 'dessin', w: 760, h: 927, ar: 0.8199, plafond_encre: 201,
        alt: 'narration graphique — collage du territoire cultivé',
        legende: 'la commune cultivée — le territoire raconté par ses jardins',
        largeur: 'tiers', index: false },
      { id: 'hpp-herbier', nature: 'herbier', type: 'dessin', w: 712, h: 937, ar: 0.7599, plafond_encre: 245,
        alt: 'herbier des espèces spontanées de la commune',
        legende: "six espèces spontanées relevées sur place, de l'origan sauvage à la digitale pourpre",
        largeur: 'tiers', index: false },
      { id: 'hpp-ref-molenbeek', nature: 'référence', type: 'photo', w: 407, h: 560, ar: 0.7268, plafond_encre: null,
        alt: 'référence — rénovation avec extension de toiture par Hé Architecture, Molenbeek 2024',
        legende: 'hé architecture, molenbeek 2024 — la maison étendue par son toit',
        largeur: 'tiers', index: false },
      { id: 'hpp-ref-melbourne', nature: 'référence', type: 'photo', w: 457, h: 560, ar: 0.8161, plafond_encre: null,
        alt: 'référence — logements ParkLife par Austin Maynard Architects, Melbourne 2022',
        legende: 'austin maynard architects, melbourne 2022 — la coursive comme lieu de vie',
        largeur: 'tiers', index: false }
    ]
  },
  /* Projets du portfolio imprimé, en préparation : titre, cadre et année non confirmés → null. */
  { slug: null, ordre: 2, etat: 'brouillon', numero: null, axe: null, titre: null, annee: null, lieu: null, documents: [] },
  { slug: null, ordre: 3, etat: 'brouillon', numero: null, axe: null, titre: null, annee: null, lieu: null, documents: [] },
  { slug: null, ordre: 4, etat: 'brouillon', numero: null, axe: null, titre: null, annee: null, lieu: null, documents: [] },
  { slug: null, ordre: 5, etat: 'brouillon', numero: null, axe: null, titre: null, annee: null, lieu: null, documents: [] }
];
